#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind -cflags -warn-error,+A" }

action ()
{
    case $1 in
        default) action lib ;;
        lib) $OCAMLBUILD hkdf.cmx ;;
        test) action lib ; $OCAMLBUILD rfctests.native ;;
        coverage)
            action clean ;
            export BISECT_COVERAGE="YES" ;
            action lib ;
            $OCAMLBUILD -pkg bisect_ppx rfctests.native ;
            ./rfctests.native ;
            bisect-ppx-report -I _build/ -html coverage/ bisect0001.out ;;
        clean) $OCAMLBUILD -clean ; rm -rf _tests ; rm -rf coverage ; rm -f bisect*.out ;;
        *) $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
