#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind"}

action ()
{
    case $1 in
        default)   $OCAMLBUILD uucp.cma uucp.cmxa ;;
        tests)     $OCAMLBUILD test/tests.otarget ;;
        doc)       shift; topkg doc --dev $* ;;
        api-doc)   shift; topkg doc $* ;;
        gen_props) $OCAMLBUILD gen_props.native ;;
        support)   pkg/build_support.ml ;;
        clean)     $OCAMLBUILD -clean
                   rm -f src/uucp_*_data.ml
                   ;;
        *)         $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
