open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F

  let hdr_init = foreign "hdr_init"
    (int64_t @-> int64_t @-> int @-> ptr (ptr Types.hdr_histogram) @->
     returning int)

  let hdr_record_value = foreign "hdr_record_value"
    (ptr Types.hdr_histogram @-> int64_t @-> returning bool)

  let hdr_close = foreign "hdr_close"
    (ptr Types.hdr_histogram @-> returning void)

  let hdr_percentiles_print = foreign "hdr_percentiles_print"
    (ptr Types.hdr_histogram @-> int64_t @-> int32_t @-> double @-> int64_t @->
     returning int)
end
