#!/bin/sh

set -e

curl -s -S -O \
 http://www.unicode.org/Public/$UNICODEVERSION/ucdxml/ucd.all.grouped.zip

unzip ucd.all.grouped.zip 
mv ucd.all.grouped.xml data/ucd.xml

./build data
./build substdata
